name: update ai collections

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.6.0
          with:
            ssh-private-key: ${{ secrets.ssh }}
      - name: run update ai collections
        run: sh automation/update_ai_collections.sh
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating ai_collections"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master